import type { Habit } from '~/types'

export const appIcons = [
	'lucide:activity',
	'lucide:star',
	'lucide:heart',
	'lucide:bomb',
	'lucide:annoyed',
	'lucide:anchor',
	'lucide:bone',
	'lucide:bell',
	'lucide:apple',
	'lucide:bug',
	'lucide:candy',
	'lucide:check',
	'lucide:carrot',
	'lucide:coffee',
	'lucide:chrome',
	'lucide:drum',
	'lucide:fingerprint',
	'lucide:ghost',
	'lucide:gem',
	'lucide:hand-metal',
	'lucide:guitar',
	'lucide:leaf',
	'lucide:party-popper',
	'lucide:paw-print',
	'lucide:piggy-bank',
	'lucide:skull',
	'lucide:pyramid',
	'lucide:message-circle',
	'lucide:chart-pie',
]
export const appColors = [
	'#FFFFCC',
	'#FFCC99',
	'#AA9499',
	'#C6A4A4',
	'#FF9899',
	'#FFCCCC',
	'#FF99CC',
	'#FFCCFF',
	'#CC99FF',
	'#CCCCFF',
	'#99CCFF',
	'#99C5C4',
	'#CCFFFF',
]

export const habits: Habit[] = [
	{
		id: 'habit-1',
		title: 'Reading',
		createdAt: '2024-03-10T09:00:00Z',
		icon: appIcons[0],
		color: appColors[5],
		days: [
			{
				id: 'day-1-1',
				habitId: 'habit-1',
				date: '2024-03-11',
				completed: true,
			},
			{
				id: 'day-1-2',
				habitId: 'habit-1',
				date: '2024-03-12',
				completed: true,
			},
			{
				id: 'day-1-3',
				habitId: 'habit-1',
				date: '2024-03-13',
				completed: false,
			},
		],
		isArchived: false,
	},
	{
		id: 'habit-2',
		title: 'Exercise',
		createdAt: '2024-03-10T09:00:00Z',
		icon: appIcons[4],
		color: appColors[7],
		days: [
			{
				id: 'day-2-1',
				habitId: 'habit-2',
				date: '2024-03-11',
				completed: true,
			},
			{
				id: 'day-2-2',
				habitId: 'habit-2',
				date: '2024-03-12',
				completed: false,
			},
			{
				id: 'day-2-3',
				habitId: 'habit-2',
				date: '2024-03-13',
				completed: false,
			},
		],
		isArchived: false,
	},
]
