import type { User } from '~/types'

export const appIcons = [
	'lucide:activity',
	'lucide:star',
	'lucide:heart',
	'lucide:bomb',
	'lucide:annoyed',
	'lucide:anchor',
	'lucide:bone',
	'lucide:bell',
	'lucide:apple',
	'lucide:bug',
	'lucide:candy',
	'lucide:check',
	'lucide:carrot',
	'lucide:coffee',
	'lucide:chrome',
	'lucide:drum',
	'lucide:fingerprint',
	'lucide:ghost',
	'lucide:gem',
	'lucide:hand-metal',
	'lucide:guitar',
	'lucide:leaf',
	'lucide:party-popper',
	'lucide:paw-print',
	'lucide:piggy-bank',
	'lucide:skull',
	'lucide:pyramid',
	'lucide:message-circle',
	'lucide:chart-pie',
]
export const appColors = [
	'#FFFFCC',
	'#FFCC99',
	'#AA9499',
	'#C6A4A4',
	'#FF9899',
	'#FFCCCC',
	'#FF99CC',
	'#FFCCFF',
	'#CC99FF',
	'#CCCCFF',
	'#99CCFF',
	'#99C5C4',
	'#CCFFFF',
]
export const initialUser: User = {
	id: null,
	email: null,
	displayName: null,
}
